export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const RSVP_START = "RSVP_START";
export const FETCH_RSVP_SUCCESS = "FETCH_RSVP_SUCCESS";
export const UPDATE_RSVP_SUCCESS = "UPDATE_RSVP_SUCCESS";
export const RSVP_FAIL = "RSVP_FAIL";
export const FETCH_EVENT_START = "FETCH_EVENT_START";
export const FETCH_EVENT_SUCCESS = "FETCH_EVENT_SUCCESS";
export const FETCH_EVENT_FAIL = "FETCH_EVENT_FAIL";
